# -*- coding: utf-8 -*-
"""Copia de Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Mbm_UFgW9_7XuR2-SHcui5np7bVqhl01
"""

print("Ingresar numero de 4 digitos")
nx=input()
print("Ingrese la cantidad de numeros aleatorios que desea")
n=input()
x_1=int(nx)
n=int(n)
Generados=[x_1]
for i in range(1,n):
  x2=x_1**2
  x_2=str(x2)
  xlis=list(x_2)
  length=len(xlis)
  a=length%2
  # CICLO PARA AGREGAR UN 0 AL INICIO DE CADA NUMERO EN CASO DE QUE SEA IMPAR
  if a==0:
    xlis=xlis
  else:
    xlis.insert(0,'0')
  b=len(xlis)
  #CICLO PARA ELEGIR LOS NUMEROS QUE SE ENCUENTRAN EN MEDIO
  if b==8:
    x=xlis[2:6]
  else:
    x=xlis[1:5]
  x_1=''.join(x)
  x_1=int(x_1)
  Generados.append(x_1)
  i=i+1
print(Generados)